# Generated by Django 4.0.3 on 2022-03-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCnpj', models.CharField(max_length=14)),
                ('RazSoci', models.CharField(max_length=255)),
                ('NomFant', models.CharField(max_length=255)),
                ('DataGer', models.DateTimeField(auto_now_add=True)),
                ('DataAut', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumCnpj', models.CharField(max_length=14)),
                ('DataCon', models.DateField(auto_now_add=True)),
                ('HoraCon', models.TimeField(auto_now_add=True)),
                ('TipoCon', models.CharField(choices=[(1, 'Telefone'), (2, 'WhatsApp'), (3, 'E-mail')], max_length=1)),
                ('SitiCon', models.CharField(choices=[(1, 'Prospecção'), (2, 'Aguardando Retorno'), (3, 'Pedido Efetivado'), (4, 'Cancelamento'), (5, 'Sem Interresse'), (6, 'Pedido Cancelado'), (7, 'Cobrança')], max_length=1)),
                ('ObseCon', models.TextField()),
            ],
        ),
    ]
